### ISSUE TITLE
Is it possible to run conditionally?

### ISSUE THREAD

**Issue by garak** [aktions/codeclimate-test-reporter#10]
I'm using this action, but I run tests many times (in different environments).
I would like to send coverage only once.

**Comment by ivanoblomov** [comment]
Try something like this:
```yml
    steps:
    - name: Code Climate coverage
       uses: aktions/codeclimate-test-reporter@v1
       if: ${{ github.event_name != 'pull_request' }}
```

**Comment by garak** [comment]
> Try something like this:
> 
> ```yaml
>     steps:
>     - name: Code Climate coverage
>        uses: aktions/codeclimate-test-reporter@v1
>        if: ${{ github.event_name != 'pull_request' }}
> ```

Thanks for your suggestion, but I don't get how it's supposed to help me.
Maybe an example can be more clear: I'm testing my code with version X, Y, and Z of my language of choice. I would like to run coverage only for X (since I'm pretty sure that it's the same with Y and with Z).

**Comment by ivanoblomov** [comment]
Hard to tell without seeing the context, but assuming it's similar to the following:
```yml
jobs:
  test:
    environment: staging
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby-version }}
    strategy:
      matrix:
        ruby-version: [2.5, 2.6, 2.7, '3.0']
    steps:
[...]
    - name: Code Climate coverage
      uses: aktions/codeclimate-test-reporter@v1
      with:
        codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
        command: after-build --coverage-input-type lcov
```
then you could add an `if` to the coverage step to run on only the desired version like so:
```yml
    - name: Code Climate coverage
      uses: aktions/codeclimate-test-reporter@v1
      if: ${{ matrix.ruby-version == '2.7' }}
      with:
        codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
        command: after-build --coverage-input-type lcov
```
