### ISSUE TITLE
Pull-request runs fail with null "pull_request"

### ISSUE THREAD

**Issue by ivanoblomov** [aktions/codeclimate-test-reporter#17]
Running tests as a GitHub Action with [`test.yml`](https://github.com/FoveaCentral/google_maps_geocoder/blob/4c236c6444bffe1609ff96036e01d6a65f57f40e/.github/workflows/test.yml):
```yml
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
[...]
    - name: Code Climate coverage
      uses: aktions/codeclimate-test-reporter@v1
      with:
        codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
        command: after-build --coverage-input-type lcov
```
fails with:
```ruby
Error: Cannot read property 'pull_request' of undefined 
```
See [complete Action output](https://github.com/FoveaCentral/google_maps_geocoder/runs/4257355960?check_suite_focus=true#step:5:1).

But note same configuration works with `push`:

![Screen Shot 2021-11-18 at 1 51 24 PM](https://user-images.githubusercontent.com/113809/142502886-665d58c4-daae-48b3-852c-593c07902cd4.png)

**Comment by ivanoblomov** [comment]
This may be related to [How does pull_request affect @actions/checkout?](https://frontside.com/blog/2020-05-26-github-actions-pull_request/#how-does-pull_request-affect-actionscheckout)

**Comment by ivanoblomov** [comment]
The solution is to make the step conditional, like so:
```yml
    - name: Code Climate coverage
       uses: aktions/codeclimate-test-reporter@v1
       if: ${{ github.event_name != 'pull_request' }}
       with:
         codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
         command: after-build --coverage-input-type lcov
```
